#include "Vadder.h"           // Generated by Verilator
#include "verilated.h"
#include "verilated_vcd_c.h"  // For waveform tracing
#include <iostream>

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);

    // Initialize tracing
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;

    Vadder* top = new Vadder;
    top->trace(tfp, 99);       // Trace 99 levels deep
    tfp->open("waveform.vcd"); // Output file

    // Simulation loop
    for (int a = 0; a < 8; ++a) {
        for (int b = 0; b < 8; ++b) {
            top->a = a;
            top->b = b;

            top->eval();      // Evaluate the model
            tfp->dump((a*8 + b) * 10); // Timestamp

            std::cout << "a=" << a
                      << " b=" << b
                      << " sum=" << (int)top->sum
                      << std::endl;
        }
    }

    // Clean up
    top->final();
    tfp->close();
    delete tfp;
    delete top;
    return 0;
}

