// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251001_170536_matrix_for_each_top_sref\hdlsrc\matrix_for_each_wrapper\matrix_foreach_adder_tree.sv
// Created: 2025-10-01 17:06:14
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import matrix_foreach_matrix_for_each_top_sref_pkg::* ;

// -------------------------------------------------------------
// 
// Module: matrix_foreach_adder_tree
// Source Path: matrix_for_each_wrapper/matrix_for_each_top_sref/matrix_for_each_0/adder_tree
// Hierarchy Level: 2
// Model version: 1.29
// 
// -------------------------------------------------------------
module matrix_foreach_adder_tree
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_mat_in[0:7]  /* ufix4 [8] */,
             input logic i_valid,
             output logic [15:0] o_value_out  /* uint16 */);


  vec_unsigned_logic_4 adder_tree_demux_0_out1 [0:3];  /* ufix4 [4] */
  vec_unsigned_logic_4 adder_tree_demux_0_out2 [0:3];  /* ufix4 [4] */
  vec_unsigned_logic_32 adder_tree_add_0_add_temp [0:3];  /* ufix32 [4] */
  vec_unsigned_logic_32 adder_tree_add_0_1 [0:3];  /* ufix32 [4] */
  vec_unsigned_logic_32 adder_tree_add_0_2 [0:3];  /* ufix32 [4] */
  vec_unsigned_logic_8 adder_tree_add_0_out1 [0:3];  /* uint8 [4] */
  vec_unsigned_logic_8 adder_tree_delay_0_out1 [0:3];  /* uint8 [4] */
  vec_unsigned_logic_8 adder_tree_demux_1_out1 [0:1];  /* uint8 [2] */
  vec_unsigned_logic_8 adder_tree_demux_1_out2 [0:1];  /* uint8 [2] */
  vec_unsigned_logic_8 adder_tree_add_1_out1 [0:1];  /* uint8 [2] */
  vec_unsigned_logic_8 adder_tree_delay_1_out1 [0:1];  /* uint8 [2] */
  logic [7:0] adder_tree_delay_1_out1_0;  /* uint8 */
  logic [7:0] adder_tree_delay_1_out1_1;  /* uint8 */
  logic [7:0] adder_tree_add_2_out1;  /* uint8 */
  logic [7:0] adder_tree_delay_2_out1;  /* uint8 */
  logic [15:0] adder_tree_dtc_out1;  /* uint16 */


  assign adder_tree_demux_0_out1[0] = i_mat_in[0];
  assign adder_tree_demux_0_out1[1] = i_mat_in[1];
  assign adder_tree_demux_0_out1[2] = i_mat_in[2];
  assign adder_tree_demux_0_out1[3] = i_mat_in[3];
  assign adder_tree_demux_0_out2[0] = i_mat_in[4];
  assign adder_tree_demux_0_out2[1] = i_mat_in[5];
  assign adder_tree_demux_0_out2[2] = i_mat_in[6];
  assign adder_tree_demux_0_out2[3] = i_mat_in[7];


  genvar t_02;
  generate
    for(t_02 = 32'sd0; t_02 <= 32'sd3; t_02 = t_02 + 32'sd1) begin:adder_tree_add_0_out1_gen
      assign adder_tree_add_0_1[t_02] = {28'b0, adder_tree_demux_0_out1[t_02]};
      assign adder_tree_add_0_2[t_02] = {28'b0, adder_tree_demux_0_out2[t_02]};
      assign adder_tree_add_0_add_temp[t_02] = adder_tree_add_0_1[t_02] + adder_tree_add_0_2[t_02];
      assign adder_tree_add_0_out1[t_02] = adder_tree_add_0_add_temp[t_02][7:0];
    end
  endgenerate
  always_ff @(posedge i_clk or negedge i_rstn)
    begin : adder_tree_delay_0_process
      if (i_rstn == 1'b0) begin
        adder_tree_delay_0_out1 <= '{4{8'b00000000}};
      end
      else begin
        if (i_valid) begin
          adder_tree_delay_0_out1 <= adder_tree_add_0_out1;
        end
      end
    end
  assign adder_tree_demux_1_out1[0] = adder_tree_delay_0_out1[0];
  assign adder_tree_demux_1_out1[1] = adder_tree_delay_0_out1[1];
  assign adder_tree_demux_1_out2[0] = adder_tree_delay_0_out1[2];
  assign adder_tree_demux_1_out2[1] = adder_tree_delay_0_out1[3];


  genvar t_011;
  generate
    for(t_011 = 32'sd0; t_011 <= 32'sd1; t_011 = t_011 + 32'sd1) begin:adder_tree_add_1_out1_gen
      assign adder_tree_add_1_out1[t_011] = adder_tree_demux_1_out1[t_011] + adder_tree_demux_1_out2[t_011];
    end
  endgenerate
  always_ff @(posedge i_clk or negedge i_rstn)
    begin : adder_tree_delay_1_process
      if (i_rstn == 1'b0) begin
        adder_tree_delay_1_out1 <= '{2{8'b00000000}};
      end
      else begin
        if (i_valid) begin
          adder_tree_delay_1_out1 <= adder_tree_add_1_out1;
        end
      end
    end
  assign adder_tree_delay_1_out1_0 = adder_tree_delay_1_out1[0];
  assign adder_tree_delay_1_out1_1 = adder_tree_delay_1_out1[1];

  assign adder_tree_add_2_out1 = adder_tree_delay_1_out1_0 + adder_tree_delay_1_out1_1;
  always_ff @(posedge i_clk or negedge i_rstn)
    begin : adder_tree_delay_2_process
      if (i_rstn == 1'b0) begin
        adder_tree_delay_2_out1 <= 8'b00000000;
      end
      else begin
        if (i_valid) begin
          adder_tree_delay_2_out1 <= adder_tree_add_2_out1;
        end
      end
    end
  assign adder_tree_dtc_out1 = {8'b0, adder_tree_delay_2_out1};
  assign o_value_out = adder_tree_dtc_out1;

endmodule  // matrix_foreach_adder_tree

