// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251001_170536_matrix_for_each_top_sref\hdlsrc\matrix_for_each_wrapper\matrix_foreach_matrix_for_each_top_sref.sv
// Created: 2025-10-01 17:06:14
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import matrix_foreach_matrix_for_each_top_sref_pkg::* ;

// -------------------------------------------------------------
// 
// Module: matrix_foreach_matrix_for_each_top_sref
// Source Path: matrix_for_each_wrapper/matrix_for_each_top_sref
// Hierarchy Level: 0
// Model version: 1.29
// 
// -------------------------------------------------------------
module matrix_foreach_matrix_for_each_top_sref
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_data_0[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_1[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_2[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_3[0:31]  /* ufix4 [32] */,
             input logic i_valid,
             output vec_unsigned_logic_16 o_data_0[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_1[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_2[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_3[0:31]  /* uint16 [32] */);


  vec_unsigned_logic_16 matrix_for_each_0_out1 [0:31];  /* uint16 [32] */
  vec_unsigned_logic_16 matrix_for_each_1_out1 [0:31];  /* uint16 [32] */
  vec_unsigned_logic_16 matrix_for_each_2_out1 [0:31];  /* uint16 [32] */
  vec_unsigned_logic_16 matrix_for_each_3_out1 [0:31];  /* uint16 [32] */


  matrix_foreach_matrix_for_each_0 u_matrix_for_each_0 (.i_clk(i_clk),
                                                        .i_rstn(i_rstn),
                                                        .i_data(i_data_0),  /* ufix4 [32] */
                                                        .i_valid(i_valid),
                                                        .o_data(matrix_for_each_0_out1)  /* uint16 [32] */
                                                        );
  assign o_data_0 = matrix_for_each_0_out1;

  matrix_foreach_matrix_for_each_0 u_matrix_for_each_1 (.i_clk(i_clk),
                                                        .i_rstn(i_rstn),
                                                        .i_data(i_data_1),  /* ufix4 [32] */
                                                        .i_valid(i_valid),
                                                        .o_data(matrix_for_each_1_out1)  /* uint16 [32] */
                                                        );
  assign o_data_1 = matrix_for_each_1_out1;

  matrix_foreach_matrix_for_each_0 u_matrix_for_each_2 (.i_clk(i_clk),
                                                        .i_rstn(i_rstn),
                                                        .i_data(i_data_2),  /* ufix4 [32] */
                                                        .i_valid(i_valid),
                                                        .o_data(matrix_for_each_2_out1)  /* uint16 [32] */
                                                        );
  assign o_data_2 = matrix_for_each_2_out1;

  matrix_foreach_matrix_for_each_0 u_matrix_for_each_3 (.i_clk(i_clk),
                                                        .i_rstn(i_rstn),
                                                        .i_data(i_data_3),  /* ufix4 [32] */
                                                        .i_valid(i_valid),
                                                        .o_data(matrix_for_each_3_out1)  /* uint16 [32] */
                                                        );
  assign o_data_3 = matrix_for_each_3_out1;

endmodule  // matrix_foreach_matrix_for_each_top_sref

