// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251001_170536_matrix_for_each_top_sref\hdlsrc\matrix_for_each_wrapper\matrix_foreach_matrix_for_each_top_sref_pkg.sv
// Created: 2025-10-01 17:06:14
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------



package matrix_foreach_matrix_for_each_top_sref_pkg;
  typedef  logic  [3:0] vec_unsigned_logic_4;

  typedef  logic  [31:0] vec_unsigned_logic_32;
  typedef  logic  [7:0] vec_unsigned_logic_8;

  typedef  logic  [15:0] vec_unsigned_logic_16;

endpackage: matrix_foreach_matrix_for_each_top_sref_pkg

