// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251001_170536_matrix_for_each_top_sref\hdlsrc\matrix_for_each_wrapper\matrix_foreach_matrix_for_each_0.sv
// Created: 2025-10-01 17:06:14
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import matrix_foreach_matrix_for_each_top_sref_pkg::* ;

// -------------------------------------------------------------
// 
// Module: matrix_foreach_matrix_for_each_0
// Source Path: matrix_for_each_wrapper/matrix_for_each_top_sref/matrix_for_each_0
// Hierarchy Level: 1
// Model version: 1.29
// 
// -------------------------------------------------------------
module matrix_foreach_matrix_for_each_0
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_data[0:31]  /* ufix4 [32] */,
             input logic i_valid,
             output vec_unsigned_logic_16 o_data[0:31]  /* uint16 [32] */);


  vec_unsigned_logic_4 create_mat_out1 [0:31] [0:7];  /* ufix4 [32x8] */
  vec_unsigned_logic_4 create_mat_out10 [0:7];  /* ufix4 [8] */
  logic create_mat_valid_prop_out1;
  logic [15:0] adder_tree_dtc_out1_0;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out11 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_1;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out12 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_2;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out13 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_3;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out14 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_4;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out15 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_5;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out16 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_6;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out17 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_7;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out18 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_8;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out19 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_9;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out110 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_10;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out111 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_11;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out112 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_12;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out113 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_13;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out114 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_14;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out115 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_15;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out116 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_16;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out117 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_17;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out118 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_18;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out119 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_19;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out120 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_20;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out121 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_21;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out122 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_22;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out123 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_23;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out124 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_24;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out125 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_25;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out126 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_26;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out127 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_27;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out128 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_28;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out129 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_29;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out130 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_30;  /* uint16 */
  vec_unsigned_logic_4 create_mat_out131 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_31;  /* uint16 */
  vec_unsigned_logic_16 adder_tree_out1 [0:31];  /* uint16 [32] */


  matrix_foreach_create_mat u_create_mat (.i_clk(i_clk),
                                          .i_rstn(i_rstn),
                                          .i_data(i_data),  /* ufix4 [32] */
                                          .i_valid(i_valid),
                                          .o_expanded_input(create_mat_out1)  /* ufix4 [32x8] */
                                          );

  genvar t_032;
  generate
    for(t_032 = 32'sd0; t_032 <= 32'sd7; t_032 = t_032 + 32'sd1) begin:create_mat_out10_gen
      assign create_mat_out10[t_032] = create_mat_out1[0][t_032];
    end
  endgenerate

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : create_mat_valid_prop_process
      if (i_rstn == 1'b0) begin
        create_mat_valid_prop_out1 <= 1'b0;
      end
      else begin
        create_mat_valid_prop_out1 <= i_valid;
      end
    end
  matrix_foreach_adder_tree u_adder_tree_instance1 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out10),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_0)  /* uint16 */
                                                    );

  genvar t_0110;
  generate
    for(t_0110 = 32'sd0; t_0110 <= 32'sd7; t_0110 = t_0110 + 32'sd1) begin:create_mat_out11_gen
      assign create_mat_out11[t_0110] = create_mat_out1[1][t_0110];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance2 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out11),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_1)  /* uint16 */
                                                    );

  genvar t_0210;
  generate
    for(t_0210 = 32'sd0; t_0210 <= 32'sd7; t_0210 = t_0210 + 32'sd1) begin:create_mat_out12_gen
      assign create_mat_out12[t_0210] = create_mat_out1[2][t_0210];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance3 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out12),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_2)  /* uint16 */
                                                    );

  genvar t_033;
  generate
    for(t_033 = 32'sd0; t_033 <= 32'sd7; t_033 = t_033 + 32'sd1) begin:create_mat_out13_gen
      assign create_mat_out13[t_033] = create_mat_out1[3][t_033];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance4 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out13),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_3)  /* uint16 */
                                                    );

  genvar t_041;
  generate
    for(t_041 = 32'sd0; t_041 <= 32'sd7; t_041 = t_041 + 32'sd1) begin:create_mat_out14_gen
      assign create_mat_out14[t_041] = create_mat_out1[4][t_041];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance5 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out14),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_4)  /* uint16 */
                                                    );

  genvar t_051;
  generate
    for(t_051 = 32'sd0; t_051 <= 32'sd7; t_051 = t_051 + 32'sd1) begin:create_mat_out15_gen
      assign create_mat_out15[t_051] = create_mat_out1[5][t_051];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance6 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out15),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_5)  /* uint16 */
                                                    );

  genvar t_061;
  generate
    for(t_061 = 32'sd0; t_061 <= 32'sd7; t_061 = t_061 + 32'sd1) begin:create_mat_out16_gen
      assign create_mat_out16[t_061] = create_mat_out1[6][t_061];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance7 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out16),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_6)  /* uint16 */
                                                    );

  genvar t_071;
  generate
    for(t_071 = 32'sd0; t_071 <= 32'sd7; t_071 = t_071 + 32'sd1) begin:create_mat_out17_gen
      assign create_mat_out17[t_071] = create_mat_out1[7][t_071];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance8 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out17),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_7)  /* uint16 */
                                                    );

  genvar t_081;
  generate
    for(t_081 = 32'sd0; t_081 <= 32'sd7; t_081 = t_081 + 32'sd1) begin:create_mat_out18_gen
      assign create_mat_out18[t_081] = create_mat_out1[8][t_081];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance9 (.i_clk(i_clk),
                                                    .i_rstn(i_rstn),
                                                    .i_mat_in(create_mat_out18),  /* ufix4 [8] */
                                                    .i_valid(create_mat_valid_prop_out1),
                                                    .o_value_out(adder_tree_dtc_out1_8)  /* uint16 */
                                                    );

  genvar t_091;
  generate
    for(t_091 = 32'sd0; t_091 <= 32'sd7; t_091 = t_091 + 32'sd1) begin:create_mat_out19_gen
      assign create_mat_out19[t_091] = create_mat_out1[9][t_091];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance10 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out19),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_9)  /* uint16 */
                                                     );

  genvar t_0101;
  generate
    for(t_0101 = 32'sd0; t_0101 <= 32'sd7; t_0101 = t_0101 + 32'sd1) begin:create_mat_out110_gen
      assign create_mat_out110[t_0101] = create_mat_out1[10][t_0101];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance11 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out110),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_10)  /* uint16 */
                                                     );

  genvar t_0111;
  generate
    for(t_0111 = 32'sd0; t_0111 <= 32'sd7; t_0111 = t_0111 + 32'sd1) begin:create_mat_out111_gen
      assign create_mat_out111[t_0111] = create_mat_out1[11][t_0111];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance12 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out111),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_11)  /* uint16 */
                                                     );

  genvar t_0121;
  generate
    for(t_0121 = 32'sd0; t_0121 <= 32'sd7; t_0121 = t_0121 + 32'sd1) begin:create_mat_out112_gen
      assign create_mat_out112[t_0121] = create_mat_out1[12][t_0121];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance13 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out112),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_12)  /* uint16 */
                                                     );

  genvar t_0131;
  generate
    for(t_0131 = 32'sd0; t_0131 <= 32'sd7; t_0131 = t_0131 + 32'sd1) begin:create_mat_out113_gen
      assign create_mat_out113[t_0131] = create_mat_out1[13][t_0131];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance14 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out113),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_13)  /* uint16 */
                                                     );

  genvar t_0141;
  generate
    for(t_0141 = 32'sd0; t_0141 <= 32'sd7; t_0141 = t_0141 + 32'sd1) begin:create_mat_out114_gen
      assign create_mat_out114[t_0141] = create_mat_out1[14][t_0141];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance15 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out114),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_14)  /* uint16 */
                                                     );

  genvar t_0151;
  generate
    for(t_0151 = 32'sd0; t_0151 <= 32'sd7; t_0151 = t_0151 + 32'sd1) begin:create_mat_out115_gen
      assign create_mat_out115[t_0151] = create_mat_out1[15][t_0151];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance16 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out115),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_15)  /* uint16 */
                                                     );

  genvar t_0161;
  generate
    for(t_0161 = 32'sd0; t_0161 <= 32'sd7; t_0161 = t_0161 + 32'sd1) begin:create_mat_out116_gen
      assign create_mat_out116[t_0161] = create_mat_out1[16][t_0161];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance17 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out116),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_16)  /* uint16 */
                                                     );

  genvar t_0171;
  generate
    for(t_0171 = 32'sd0; t_0171 <= 32'sd7; t_0171 = t_0171 + 32'sd1) begin:create_mat_out117_gen
      assign create_mat_out117[t_0171] = create_mat_out1[17][t_0171];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance18 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out117),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_17)  /* uint16 */
                                                     );

  genvar t_0181;
  generate
    for(t_0181 = 32'sd0; t_0181 <= 32'sd7; t_0181 = t_0181 + 32'sd1) begin:create_mat_out118_gen
      assign create_mat_out118[t_0181] = create_mat_out1[18][t_0181];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance19 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out118),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_18)  /* uint16 */
                                                     );

  genvar t_0191;
  generate
    for(t_0191 = 32'sd0; t_0191 <= 32'sd7; t_0191 = t_0191 + 32'sd1) begin:create_mat_out119_gen
      assign create_mat_out119[t_0191] = create_mat_out1[19][t_0191];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance20 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out119),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_19)  /* uint16 */
                                                     );

  genvar t_0201;
  generate
    for(t_0201 = 32'sd0; t_0201 <= 32'sd7; t_0201 = t_0201 + 32'sd1) begin:create_mat_out120_gen
      assign create_mat_out120[t_0201] = create_mat_out1[20][t_0201];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance21 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out120),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_20)  /* uint16 */
                                                     );

  genvar t_0211;
  generate
    for(t_0211 = 32'sd0; t_0211 <= 32'sd7; t_0211 = t_0211 + 32'sd1) begin:create_mat_out121_gen
      assign create_mat_out121[t_0211] = create_mat_out1[21][t_0211];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance22 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out121),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_21)  /* uint16 */
                                                     );

  genvar t_0221;
  generate
    for(t_0221 = 32'sd0; t_0221 <= 32'sd7; t_0221 = t_0221 + 32'sd1) begin:create_mat_out122_gen
      assign create_mat_out122[t_0221] = create_mat_out1[22][t_0221];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance23 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out122),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_22)  /* uint16 */
                                                     );

  genvar t_0231;
  generate
    for(t_0231 = 32'sd0; t_0231 <= 32'sd7; t_0231 = t_0231 + 32'sd1) begin:create_mat_out123_gen
      assign create_mat_out123[t_0231] = create_mat_out1[23][t_0231];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance24 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out123),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_23)  /* uint16 */
                                                     );

  genvar t_0241;
  generate
    for(t_0241 = 32'sd0; t_0241 <= 32'sd7; t_0241 = t_0241 + 32'sd1) begin:create_mat_out124_gen
      assign create_mat_out124[t_0241] = create_mat_out1[24][t_0241];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance25 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out124),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_24)  /* uint16 */
                                                     );

  genvar t_0251;
  generate
    for(t_0251 = 32'sd0; t_0251 <= 32'sd7; t_0251 = t_0251 + 32'sd1) begin:create_mat_out125_gen
      assign create_mat_out125[t_0251] = create_mat_out1[25][t_0251];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance26 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out125),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_25)  /* uint16 */
                                                     );

  genvar t_0261;
  generate
    for(t_0261 = 32'sd0; t_0261 <= 32'sd7; t_0261 = t_0261 + 32'sd1) begin:create_mat_out126_gen
      assign create_mat_out126[t_0261] = create_mat_out1[26][t_0261];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance27 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out126),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_26)  /* uint16 */
                                                     );

  genvar t_0271;
  generate
    for(t_0271 = 32'sd0; t_0271 <= 32'sd7; t_0271 = t_0271 + 32'sd1) begin:create_mat_out127_gen
      assign create_mat_out127[t_0271] = create_mat_out1[27][t_0271];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance28 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out127),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_27)  /* uint16 */
                                                     );

  genvar t_0281;
  generate
    for(t_0281 = 32'sd0; t_0281 <= 32'sd7; t_0281 = t_0281 + 32'sd1) begin:create_mat_out128_gen
      assign create_mat_out128[t_0281] = create_mat_out1[28][t_0281];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance29 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out128),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_28)  /* uint16 */
                                                     );

  genvar t_0291;
  generate
    for(t_0291 = 32'sd0; t_0291 <= 32'sd7; t_0291 = t_0291 + 32'sd1) begin:create_mat_out129_gen
      assign create_mat_out129[t_0291] = create_mat_out1[29][t_0291];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance30 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out129),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_29)  /* uint16 */
                                                     );

  genvar t_0301;
  generate
    for(t_0301 = 32'sd0; t_0301 <= 32'sd7; t_0301 = t_0301 + 32'sd1) begin:create_mat_out130_gen
      assign create_mat_out130[t_0301] = create_mat_out1[30][t_0301];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance31 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out130),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_30)  /* uint16 */
                                                     );

  genvar t_0311;
  generate
    for(t_0311 = 32'sd0; t_0311 <= 32'sd7; t_0311 = t_0311 + 32'sd1) begin:create_mat_out131_gen
      assign create_mat_out131[t_0311] = create_mat_out1[31][t_0311];
    end
  endgenerate

  matrix_foreach_adder_tree u_adder_tree_instance32 (.i_clk(i_clk),
                                                     .i_rstn(i_rstn),
                                                     .i_mat_in(create_mat_out131),  /* ufix4 [8] */
                                                     .i_valid(create_mat_valid_prop_out1),
                                                     .o_value_out(adder_tree_dtc_out1_31)  /* uint16 */
                                                     );
  assign adder_tree_out1[0] = adder_tree_dtc_out1_0;
  assign adder_tree_out1[1] = adder_tree_dtc_out1_1;
  assign adder_tree_out1[2] = adder_tree_dtc_out1_2;
  assign adder_tree_out1[3] = adder_tree_dtc_out1_3;
  assign adder_tree_out1[4] = adder_tree_dtc_out1_4;
  assign adder_tree_out1[5] = adder_tree_dtc_out1_5;
  assign adder_tree_out1[6] = adder_tree_dtc_out1_6;
  assign adder_tree_out1[7] = adder_tree_dtc_out1_7;
  assign adder_tree_out1[8] = adder_tree_dtc_out1_8;
  assign adder_tree_out1[9] = adder_tree_dtc_out1_9;
  assign adder_tree_out1[10] = adder_tree_dtc_out1_10;
  assign adder_tree_out1[11] = adder_tree_dtc_out1_11;
  assign adder_tree_out1[12] = adder_tree_dtc_out1_12;
  assign adder_tree_out1[13] = adder_tree_dtc_out1_13;
  assign adder_tree_out1[14] = adder_tree_dtc_out1_14;
  assign adder_tree_out1[15] = adder_tree_dtc_out1_15;
  assign adder_tree_out1[16] = adder_tree_dtc_out1_16;
  assign adder_tree_out1[17] = adder_tree_dtc_out1_17;
  assign adder_tree_out1[18] = adder_tree_dtc_out1_18;
  assign adder_tree_out1[19] = adder_tree_dtc_out1_19;
  assign adder_tree_out1[20] = adder_tree_dtc_out1_20;
  assign adder_tree_out1[21] = adder_tree_dtc_out1_21;
  assign adder_tree_out1[22] = adder_tree_dtc_out1_22;
  assign adder_tree_out1[23] = adder_tree_dtc_out1_23;
  assign adder_tree_out1[24] = adder_tree_dtc_out1_24;
  assign adder_tree_out1[25] = adder_tree_dtc_out1_25;
  assign adder_tree_out1[26] = adder_tree_dtc_out1_26;
  assign adder_tree_out1[27] = adder_tree_dtc_out1_27;
  assign adder_tree_out1[28] = adder_tree_dtc_out1_28;
  assign adder_tree_out1[29] = adder_tree_dtc_out1_29;
  assign adder_tree_out1[30] = adder_tree_dtc_out1_30;
  assign adder_tree_out1[31] = adder_tree_dtc_out1_31;

  assign o_data = adder_tree_out1;

endmodule  // matrix_foreach_matrix_for_each_0

