// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251028_144629_matrix_for_each_top\hdlsrc\matrix_for_each_wrapper\mf_create_mat.sv
// Created: 2025-10-28 14:46:55
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import mf_matrix_for_each_top_pkg::* ;

// -------------------------------------------------------------
// 
// Module: mf_create_mat
// Source Path: matrix_for_each_wrapper/matrix_for_each_top/matrix_for_each_0/create_mat
// Hierarchy Level: 2
// Model version: 3.3
// 
// -------------------------------------------------------------
module mf_create_mat
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_data[0:31]  /* ufix4 [32] */,
             input logic i_valid,
             output vec_unsigned_logic_4 o_expanded_input[0:31] [0:7]  /* ufix4 [32x8] */);


  vec_unsigned_logic_4 expand_input_out1_0 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_1 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_1 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_2 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_2 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_3 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_3 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_4 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_4 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_5 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_5 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_6 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_6 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_out1_7 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_7 [0:31];  /* ufix4 [32] */
  vec_unsigned_logic_4 expand_input_delay_out1_8 [0:31] [0:7];  /* ufix4 [32x8] */


  assign expand_input_out1_0[0] = i_data[0];
  assign expand_input_out1_0[1] = i_data[1];
  assign expand_input_out1_0[2] = i_data[2];
  assign expand_input_out1_0[3] = i_data[3];
  assign expand_input_out1_0[4] = i_data[4];
  assign expand_input_out1_0[5] = i_data[5];
  assign expand_input_out1_0[6] = i_data[6];
  assign expand_input_out1_0[7] = i_data[7];
  assign expand_input_out1_0[8] = i_data[8];
  assign expand_input_out1_0[9] = i_data[9];
  assign expand_input_out1_0[10] = i_data[10];
  assign expand_input_out1_0[11] = i_data[11];
  assign expand_input_out1_0[12] = i_data[12];
  assign expand_input_out1_0[13] = i_data[13];
  assign expand_input_out1_0[14] = i_data[14];
  assign expand_input_out1_0[15] = i_data[15];
  assign expand_input_out1_0[16] = i_data[16];
  assign expand_input_out1_0[17] = i_data[17];
  assign expand_input_out1_0[18] = i_data[18];
  assign expand_input_out1_0[19] = i_data[19];
  assign expand_input_out1_0[20] = i_data[20];
  assign expand_input_out1_0[21] = i_data[21];
  assign expand_input_out1_0[22] = i_data[22];
  assign expand_input_out1_0[23] = i_data[23];
  assign expand_input_out1_0[24] = i_data[24];
  assign expand_input_out1_0[25] = i_data[25];
  assign expand_input_out1_0[26] = i_data[26];
  assign expand_input_out1_0[27] = i_data[27];
  assign expand_input_out1_0[28] = i_data[28];
  assign expand_input_out1_0[29] = i_data[29];
  assign expand_input_out1_0[30] = i_data[30];
  assign expand_input_out1_0[31] = i_data[31];
  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1 <= expand_input_out1_0;
        end
      end
    end

  assign expand_input_out1_1[0] = i_data[0];
  assign expand_input_out1_1[1] = i_data[1];
  assign expand_input_out1_1[2] = i_data[2];
  assign expand_input_out1_1[3] = i_data[3];
  assign expand_input_out1_1[4] = i_data[4];
  assign expand_input_out1_1[5] = i_data[5];
  assign expand_input_out1_1[6] = i_data[6];
  assign expand_input_out1_1[7] = i_data[7];
  assign expand_input_out1_1[8] = i_data[8];
  assign expand_input_out1_1[9] = i_data[9];
  assign expand_input_out1_1[10] = i_data[10];
  assign expand_input_out1_1[11] = i_data[11];
  assign expand_input_out1_1[12] = i_data[12];
  assign expand_input_out1_1[13] = i_data[13];
  assign expand_input_out1_1[14] = i_data[14];
  assign expand_input_out1_1[15] = i_data[15];
  assign expand_input_out1_1[16] = i_data[16];
  assign expand_input_out1_1[17] = i_data[17];
  assign expand_input_out1_1[18] = i_data[18];
  assign expand_input_out1_1[19] = i_data[19];
  assign expand_input_out1_1[20] = i_data[20];
  assign expand_input_out1_1[21] = i_data[21];
  assign expand_input_out1_1[22] = i_data[22];
  assign expand_input_out1_1[23] = i_data[23];
  assign expand_input_out1_1[24] = i_data[24];
  assign expand_input_out1_1[25] = i_data[25];
  assign expand_input_out1_1[26] = i_data[26];
  assign expand_input_out1_1[27] = i_data[27];
  assign expand_input_out1_1[28] = i_data[28];
  assign expand_input_out1_1[29] = i_data[29];
  assign expand_input_out1_1[30] = i_data[30];
  assign expand_input_out1_1[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_1_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_1 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_1 <= expand_input_out1_1;
        end
      end
    end

  assign expand_input_out1_2[0] = i_data[0];
  assign expand_input_out1_2[1] = i_data[1];
  assign expand_input_out1_2[2] = i_data[2];
  assign expand_input_out1_2[3] = i_data[3];
  assign expand_input_out1_2[4] = i_data[4];
  assign expand_input_out1_2[5] = i_data[5];
  assign expand_input_out1_2[6] = i_data[6];
  assign expand_input_out1_2[7] = i_data[7];
  assign expand_input_out1_2[8] = i_data[8];
  assign expand_input_out1_2[9] = i_data[9];
  assign expand_input_out1_2[10] = i_data[10];
  assign expand_input_out1_2[11] = i_data[11];
  assign expand_input_out1_2[12] = i_data[12];
  assign expand_input_out1_2[13] = i_data[13];
  assign expand_input_out1_2[14] = i_data[14];
  assign expand_input_out1_2[15] = i_data[15];
  assign expand_input_out1_2[16] = i_data[16];
  assign expand_input_out1_2[17] = i_data[17];
  assign expand_input_out1_2[18] = i_data[18];
  assign expand_input_out1_2[19] = i_data[19];
  assign expand_input_out1_2[20] = i_data[20];
  assign expand_input_out1_2[21] = i_data[21];
  assign expand_input_out1_2[22] = i_data[22];
  assign expand_input_out1_2[23] = i_data[23];
  assign expand_input_out1_2[24] = i_data[24];
  assign expand_input_out1_2[25] = i_data[25];
  assign expand_input_out1_2[26] = i_data[26];
  assign expand_input_out1_2[27] = i_data[27];
  assign expand_input_out1_2[28] = i_data[28];
  assign expand_input_out1_2[29] = i_data[29];
  assign expand_input_out1_2[30] = i_data[30];
  assign expand_input_out1_2[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_2_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_2 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_2 <= expand_input_out1_2;
        end
      end
    end

  assign expand_input_out1_3[0] = i_data[0];
  assign expand_input_out1_3[1] = i_data[1];
  assign expand_input_out1_3[2] = i_data[2];
  assign expand_input_out1_3[3] = i_data[3];
  assign expand_input_out1_3[4] = i_data[4];
  assign expand_input_out1_3[5] = i_data[5];
  assign expand_input_out1_3[6] = i_data[6];
  assign expand_input_out1_3[7] = i_data[7];
  assign expand_input_out1_3[8] = i_data[8];
  assign expand_input_out1_3[9] = i_data[9];
  assign expand_input_out1_3[10] = i_data[10];
  assign expand_input_out1_3[11] = i_data[11];
  assign expand_input_out1_3[12] = i_data[12];
  assign expand_input_out1_3[13] = i_data[13];
  assign expand_input_out1_3[14] = i_data[14];
  assign expand_input_out1_3[15] = i_data[15];
  assign expand_input_out1_3[16] = i_data[16];
  assign expand_input_out1_3[17] = i_data[17];
  assign expand_input_out1_3[18] = i_data[18];
  assign expand_input_out1_3[19] = i_data[19];
  assign expand_input_out1_3[20] = i_data[20];
  assign expand_input_out1_3[21] = i_data[21];
  assign expand_input_out1_3[22] = i_data[22];
  assign expand_input_out1_3[23] = i_data[23];
  assign expand_input_out1_3[24] = i_data[24];
  assign expand_input_out1_3[25] = i_data[25];
  assign expand_input_out1_3[26] = i_data[26];
  assign expand_input_out1_3[27] = i_data[27];
  assign expand_input_out1_3[28] = i_data[28];
  assign expand_input_out1_3[29] = i_data[29];
  assign expand_input_out1_3[30] = i_data[30];
  assign expand_input_out1_3[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_3_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_3 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_3 <= expand_input_out1_3;
        end
      end
    end

  assign expand_input_out1_4[0] = i_data[0];
  assign expand_input_out1_4[1] = i_data[1];
  assign expand_input_out1_4[2] = i_data[2];
  assign expand_input_out1_4[3] = i_data[3];
  assign expand_input_out1_4[4] = i_data[4];
  assign expand_input_out1_4[5] = i_data[5];
  assign expand_input_out1_4[6] = i_data[6];
  assign expand_input_out1_4[7] = i_data[7];
  assign expand_input_out1_4[8] = i_data[8];
  assign expand_input_out1_4[9] = i_data[9];
  assign expand_input_out1_4[10] = i_data[10];
  assign expand_input_out1_4[11] = i_data[11];
  assign expand_input_out1_4[12] = i_data[12];
  assign expand_input_out1_4[13] = i_data[13];
  assign expand_input_out1_4[14] = i_data[14];
  assign expand_input_out1_4[15] = i_data[15];
  assign expand_input_out1_4[16] = i_data[16];
  assign expand_input_out1_4[17] = i_data[17];
  assign expand_input_out1_4[18] = i_data[18];
  assign expand_input_out1_4[19] = i_data[19];
  assign expand_input_out1_4[20] = i_data[20];
  assign expand_input_out1_4[21] = i_data[21];
  assign expand_input_out1_4[22] = i_data[22];
  assign expand_input_out1_4[23] = i_data[23];
  assign expand_input_out1_4[24] = i_data[24];
  assign expand_input_out1_4[25] = i_data[25];
  assign expand_input_out1_4[26] = i_data[26];
  assign expand_input_out1_4[27] = i_data[27];
  assign expand_input_out1_4[28] = i_data[28];
  assign expand_input_out1_4[29] = i_data[29];
  assign expand_input_out1_4[30] = i_data[30];
  assign expand_input_out1_4[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_4_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_4 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_4 <= expand_input_out1_4;
        end
      end
    end

  assign expand_input_out1_5[0] = i_data[0];
  assign expand_input_out1_5[1] = i_data[1];
  assign expand_input_out1_5[2] = i_data[2];
  assign expand_input_out1_5[3] = i_data[3];
  assign expand_input_out1_5[4] = i_data[4];
  assign expand_input_out1_5[5] = i_data[5];
  assign expand_input_out1_5[6] = i_data[6];
  assign expand_input_out1_5[7] = i_data[7];
  assign expand_input_out1_5[8] = i_data[8];
  assign expand_input_out1_5[9] = i_data[9];
  assign expand_input_out1_5[10] = i_data[10];
  assign expand_input_out1_5[11] = i_data[11];
  assign expand_input_out1_5[12] = i_data[12];
  assign expand_input_out1_5[13] = i_data[13];
  assign expand_input_out1_5[14] = i_data[14];
  assign expand_input_out1_5[15] = i_data[15];
  assign expand_input_out1_5[16] = i_data[16];
  assign expand_input_out1_5[17] = i_data[17];
  assign expand_input_out1_5[18] = i_data[18];
  assign expand_input_out1_5[19] = i_data[19];
  assign expand_input_out1_5[20] = i_data[20];
  assign expand_input_out1_5[21] = i_data[21];
  assign expand_input_out1_5[22] = i_data[22];
  assign expand_input_out1_5[23] = i_data[23];
  assign expand_input_out1_5[24] = i_data[24];
  assign expand_input_out1_5[25] = i_data[25];
  assign expand_input_out1_5[26] = i_data[26];
  assign expand_input_out1_5[27] = i_data[27];
  assign expand_input_out1_5[28] = i_data[28];
  assign expand_input_out1_5[29] = i_data[29];
  assign expand_input_out1_5[30] = i_data[30];
  assign expand_input_out1_5[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_5_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_5 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_5 <= expand_input_out1_5;
        end
      end
    end

  assign expand_input_out1_6[0] = i_data[0];
  assign expand_input_out1_6[1] = i_data[1];
  assign expand_input_out1_6[2] = i_data[2];
  assign expand_input_out1_6[3] = i_data[3];
  assign expand_input_out1_6[4] = i_data[4];
  assign expand_input_out1_6[5] = i_data[5];
  assign expand_input_out1_6[6] = i_data[6];
  assign expand_input_out1_6[7] = i_data[7];
  assign expand_input_out1_6[8] = i_data[8];
  assign expand_input_out1_6[9] = i_data[9];
  assign expand_input_out1_6[10] = i_data[10];
  assign expand_input_out1_6[11] = i_data[11];
  assign expand_input_out1_6[12] = i_data[12];
  assign expand_input_out1_6[13] = i_data[13];
  assign expand_input_out1_6[14] = i_data[14];
  assign expand_input_out1_6[15] = i_data[15];
  assign expand_input_out1_6[16] = i_data[16];
  assign expand_input_out1_6[17] = i_data[17];
  assign expand_input_out1_6[18] = i_data[18];
  assign expand_input_out1_6[19] = i_data[19];
  assign expand_input_out1_6[20] = i_data[20];
  assign expand_input_out1_6[21] = i_data[21];
  assign expand_input_out1_6[22] = i_data[22];
  assign expand_input_out1_6[23] = i_data[23];
  assign expand_input_out1_6[24] = i_data[24];
  assign expand_input_out1_6[25] = i_data[25];
  assign expand_input_out1_6[26] = i_data[26];
  assign expand_input_out1_6[27] = i_data[27];
  assign expand_input_out1_6[28] = i_data[28];
  assign expand_input_out1_6[29] = i_data[29];
  assign expand_input_out1_6[30] = i_data[30];
  assign expand_input_out1_6[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_6_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_6 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_6 <= expand_input_out1_6;
        end
      end
    end

  assign expand_input_out1_7[0] = i_data[0];
  assign expand_input_out1_7[1] = i_data[1];
  assign expand_input_out1_7[2] = i_data[2];
  assign expand_input_out1_7[3] = i_data[3];
  assign expand_input_out1_7[4] = i_data[4];
  assign expand_input_out1_7[5] = i_data[5];
  assign expand_input_out1_7[6] = i_data[6];
  assign expand_input_out1_7[7] = i_data[7];
  assign expand_input_out1_7[8] = i_data[8];
  assign expand_input_out1_7[9] = i_data[9];
  assign expand_input_out1_7[10] = i_data[10];
  assign expand_input_out1_7[11] = i_data[11];
  assign expand_input_out1_7[12] = i_data[12];
  assign expand_input_out1_7[13] = i_data[13];
  assign expand_input_out1_7[14] = i_data[14];
  assign expand_input_out1_7[15] = i_data[15];
  assign expand_input_out1_7[16] = i_data[16];
  assign expand_input_out1_7[17] = i_data[17];
  assign expand_input_out1_7[18] = i_data[18];
  assign expand_input_out1_7[19] = i_data[19];
  assign expand_input_out1_7[20] = i_data[20];
  assign expand_input_out1_7[21] = i_data[21];
  assign expand_input_out1_7[22] = i_data[22];
  assign expand_input_out1_7[23] = i_data[23];
  assign expand_input_out1_7[24] = i_data[24];
  assign expand_input_out1_7[25] = i_data[25];
  assign expand_input_out1_7[26] = i_data[26];
  assign expand_input_out1_7[27] = i_data[27];
  assign expand_input_out1_7[28] = i_data[28];
  assign expand_input_out1_7[29] = i_data[29];
  assign expand_input_out1_7[30] = i_data[30];
  assign expand_input_out1_7[31] = i_data[31];

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : expand_input_delay_7_process
      if (i_rstn == 1'b0) begin
        expand_input_delay_out1_7 <= '{32{4'b0000}};
      end
      else begin
        if (i_valid) begin
          expand_input_delay_out1_7 <= expand_input_out1_7;
        end
      end
    end

  generate
    genvar idx;
    for(idx = 0; idx < 32; idx = idx + 1) begin : expand_input_delay_out1_8_gen
      assign expand_input_delay_out1_8[idx][0] = expand_input_delay_out1[idx];
    end
  endgenerate
  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 32; idx1 = idx1 + 1) begin : expand_input_delay_out1_8_gen1
      assign expand_input_delay_out1_8[idx1][1] = expand_input_delay_out1_1[idx1];
    end
  endgenerate
  generate
    genvar idx2;
    for(idx2 = 0; idx2 < 32; idx2 = idx2 + 1) begin : expand_input_delay_out1_8_gen2
      assign expand_input_delay_out1_8[idx2][2] = expand_input_delay_out1_2[idx2];
    end
  endgenerate
  generate
    genvar idx3;
    for(idx3 = 0; idx3 < 32; idx3 = idx3 + 1) begin : expand_input_delay_out1_8_gen3
      assign expand_input_delay_out1_8[idx3][3] = expand_input_delay_out1_3[idx3];
    end
  endgenerate
  generate
    genvar idx4;
    for(idx4 = 0; idx4 < 32; idx4 = idx4 + 1) begin : expand_input_delay_out1_8_gen4
      assign expand_input_delay_out1_8[idx4][4] = expand_input_delay_out1_4[idx4];
    end
  endgenerate
  generate
    genvar idx5;
    for(idx5 = 0; idx5 < 32; idx5 = idx5 + 1) begin : expand_input_delay_out1_8_gen5
      assign expand_input_delay_out1_8[idx5][5] = expand_input_delay_out1_5[idx5];
    end
  endgenerate
  generate
    genvar idx6;
    for(idx6 = 0; idx6 < 32; idx6 = idx6 + 1) begin : expand_input_delay_out1_8_gen6
      assign expand_input_delay_out1_8[idx6][6] = expand_input_delay_out1_6[idx6];
    end
  endgenerate
  generate
    genvar idx7;
    for(idx7 = 0; idx7 < 32; idx7 = idx7 + 1) begin : expand_input_delay_out1_8_gen7
      assign expand_input_delay_out1_8[idx7][7] = expand_input_delay_out1_7[idx7];
    end
  endgenerate
  assign o_expanded_input = expand_input_delay_out1_8;

endmodule  // mf_create_mat

