// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251028_144629_matrix_for_each_top\hdlsrc\matrix_for_each_wrapper\mf_matrix_for_each_top.sv
// Created: 2025-10-28 14:46:55
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import mf_matrix_for_each_top_pkg::* ;

// -------------------------------------------------------------
// 
// Module: mf_matrix_for_each_top
// Source Path: matrix_for_each_wrapper/matrix_for_each_top
// Hierarchy Level: 0
// Model version: 3.3
// 
// -------------------------------------------------------------
module mf_matrix_for_each_top
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_data_0[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_1[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_2[0:31]  /* ufix4 [32] */,
             input vec_unsigned_logic_4 i_data_3[0:31]  /* ufix4 [32] */,
             input logic i_valid,
             output vec_unsigned_logic_16 o_data_0[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_1[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_2[0:31]  /* uint16 [32] */,
             output vec_unsigned_logic_16 o_data_3[0:31]  /* uint16 [32] */,
             output logic o_valid);


  vec_unsigned_logic_16 matrix_for_each_0_o_data [0:31];  /* uint16 [32] */
  logic matrix_for_each_0_o_valid;
  vec_unsigned_logic_16 matrix_for_each_1_o_data [0:31];  /* uint16 [32] */
  logic matrix_for_each_1_o_validdeadOut;
  vec_unsigned_logic_16 matrix_for_each_2_o_data [0:31];  /* uint16 [32] */
  logic matrix_for_each_2_o_validdeadOut;
  vec_unsigned_logic_16 matrix_for_each_3_o_data [0:31];  /* uint16 [32] */
  logic matrix_for_each_3_o_validdeadOut;


  mf_matrix_for_each_0 u_matrix_for_each_0 (.i_clk(i_clk),
                                            .i_rstn(i_rstn),
                                            .i_data(i_data_0),  /* ufix4 [32] */
                                            .i_valid(i_valid),
                                            .o_data(matrix_for_each_0_o_data),  /* uint16 [32] */
                                            .o_valid(matrix_for_each_0_o_valid)
                                            );
  assign o_data_0 = matrix_for_each_0_o_data;

  mf_matrix_for_each_0 u_matrix_for_each_1 (.i_clk(i_clk),
                                            .i_rstn(i_rstn),
                                            .i_data(i_data_1),  /* ufix4 [32] */
                                            .i_valid(i_valid),
                                            .o_data(matrix_for_each_1_o_data),  /* uint16 [32] */
                                            .o_valid(matrix_for_each_1_o_validdeadOut)
                                            );
  assign o_data_1 = matrix_for_each_1_o_data;

  mf_matrix_for_each_0 u_matrix_for_each_2 (.i_clk(i_clk),
                                            .i_rstn(i_rstn),
                                            .i_data(i_data_2),  /* ufix4 [32] */
                                            .i_valid(i_valid),
                                            .o_data(matrix_for_each_2_o_data),  /* uint16 [32] */
                                            .o_valid(matrix_for_each_2_o_validdeadOut)
                                            );
  assign o_data_2 = matrix_for_each_2_o_data;

  mf_matrix_for_each_0 u_matrix_for_each_3 (.i_clk(i_clk),
                                            .i_rstn(i_rstn),
                                            .i_data(i_data_3),  /* ufix4 [32] */
                                            .i_valid(i_valid),
                                            .o_data(matrix_for_each_3_o_data),  /* uint16 [32] */
                                            .o_valid(matrix_for_each_3_o_validdeadOut)
                                            );
  assign o_data_3 = matrix_for_each_3_o_data;

  assign o_valid = matrix_for_each_0_o_valid;

endmodule  // mf_matrix_for_each_top

