// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251028_144629_matrix_for_each_top\hdlsrc\matrix_for_each_wrapper\mf_matrix_for_each_0.sv
// Created: 2025-10-28 14:46:55
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------


import mf_matrix_for_each_top_pkg::* ;

// -------------------------------------------------------------
// 
// Module: mf_matrix_for_each_0
// Source Path: matrix_for_each_wrapper/matrix_for_each_top/matrix_for_each_0
// Hierarchy Level: 1
// Model version: 3.3
// 
// -------------------------------------------------------------
module mf_matrix_for_each_0
          (  input logic i_clk,
             input logic i_rstn,
             input vec_unsigned_logic_4 i_data[0:31]  /* ufix4 [32] */,
             input logic i_valid,
             output vec_unsigned_logic_16 o_data[0:31]  /* uint16 [32] */,
             output logic o_valid);


  vec_unsigned_logic_4 create_mat_o_expanded_input [0:31] [0:7];  /* ufix4 [32x8] */
  vec_unsigned_logic_4 create_mat_o_expanded_input0 [0:7];  /* ufix4 [8] */
  logic create_mat_valid_prop_out1;
  logic [15:0] adder_tree_dtc_out1_0;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input1 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_1;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input2 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_2;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input3 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_3;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input4 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_4;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input5 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_5;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input6 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_6;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input7 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_7;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input8 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_8;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input9 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_9;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input10 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_10;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input11 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_11;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input12 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_12;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input13 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_13;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input14 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_14;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input15 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_15;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input16 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_16;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input17 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_17;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input18 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_18;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input19 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_19;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input20 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_20;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input21 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_21;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input22 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_22;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input23 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_23;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input24 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_24;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input25 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_25;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input26 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_26;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input27 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_27;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input28 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_28;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input29 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_29;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input30 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_30;  /* uint16 */
  vec_unsigned_logic_4 create_mat_o_expanded_input31 [0:7];  /* ufix4 [8] */
  logic [15:0] adder_tree_dtc_out1_31;  /* uint16 */
  vec_unsigned_logic_16 adder_tree_o_value_out [0:31];  /* uint16 [32] */
  logic [2:0] adder_tree_valid_prop_reg;  /* ufix1 [3] */
  logic adder_tree_valid_prop_out1;


  mf_create_mat u_create_mat (.i_clk(i_clk),
                              .i_rstn(i_rstn),
                              .i_data(i_data),  /* ufix4 [32] */
                              .i_valid(i_valid),
                              .o_expanded_input(create_mat_o_expanded_input)  /* ufix4 [32x8] */
                              );

  genvar t_0;
  generate
    for(t_0 = 32'sd0; t_0 <= 32'sd7; t_0 = t_0 + 32'sd1) begin:create_mat_o_expanded_input0_gen
      assign create_mat_o_expanded_input0[t_0] = create_mat_o_expanded_input[0][t_0];
    end
  endgenerate

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : create_mat_valid_prop_process
      if (i_rstn == 1'b0) begin
        create_mat_valid_prop_out1 <= 1'b0;
      end
      else begin
        create_mat_valid_prop_out1 <= i_valid;
      end
    end
  mf_adder_tree u_adder_tree_instance1 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input0),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_0)  /* uint16 */
                                        );

  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd7; t_01 = t_01 + 32'sd1) begin:create_mat_o_expanded_input1_gen
      assign create_mat_o_expanded_input1[t_01] = create_mat_o_expanded_input[1][t_01];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance2 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input1),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_1)  /* uint16 */
                                        );

  genvar t_02;
  generate
    for(t_02 = 32'sd0; t_02 <= 32'sd7; t_02 = t_02 + 32'sd1) begin:create_mat_o_expanded_input2_gen
      assign create_mat_o_expanded_input2[t_02] = create_mat_o_expanded_input[2][t_02];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance3 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input2),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_2)  /* uint16 */
                                        );

  genvar t_03;
  generate
    for(t_03 = 32'sd0; t_03 <= 32'sd7; t_03 = t_03 + 32'sd1) begin:create_mat_o_expanded_input3_gen
      assign create_mat_o_expanded_input3[t_03] = create_mat_o_expanded_input[3][t_03];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance4 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input3),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_3)  /* uint16 */
                                        );

  genvar t_04;
  generate
    for(t_04 = 32'sd0; t_04 <= 32'sd7; t_04 = t_04 + 32'sd1) begin:create_mat_o_expanded_input4_gen
      assign create_mat_o_expanded_input4[t_04] = create_mat_o_expanded_input[4][t_04];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance5 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input4),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_4)  /* uint16 */
                                        );

  genvar t_05;
  generate
    for(t_05 = 32'sd0; t_05 <= 32'sd7; t_05 = t_05 + 32'sd1) begin:create_mat_o_expanded_input5_gen
      assign create_mat_o_expanded_input5[t_05] = create_mat_o_expanded_input[5][t_05];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance6 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input5),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_5)  /* uint16 */
                                        );

  genvar t_06;
  generate
    for(t_06 = 32'sd0; t_06 <= 32'sd7; t_06 = t_06 + 32'sd1) begin:create_mat_o_expanded_input6_gen
      assign create_mat_o_expanded_input6[t_06] = create_mat_o_expanded_input[6][t_06];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance7 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input6),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_6)  /* uint16 */
                                        );

  genvar t_07;
  generate
    for(t_07 = 32'sd0; t_07 <= 32'sd7; t_07 = t_07 + 32'sd1) begin:create_mat_o_expanded_input7_gen
      assign create_mat_o_expanded_input7[t_07] = create_mat_o_expanded_input[7][t_07];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance8 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input7),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_7)  /* uint16 */
                                        );

  genvar t_08;
  generate
    for(t_08 = 32'sd0; t_08 <= 32'sd7; t_08 = t_08 + 32'sd1) begin:create_mat_o_expanded_input8_gen
      assign create_mat_o_expanded_input8[t_08] = create_mat_o_expanded_input[8][t_08];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance9 (.i_clk(i_clk),
                                        .i_rstn(i_rstn),
                                        .i_mat_in(create_mat_o_expanded_input8),  /* ufix4 [8] */
                                        .i_valid(create_mat_valid_prop_out1),
                                        .o_value_out(adder_tree_dtc_out1_8)  /* uint16 */
                                        );

  genvar t_09;
  generate
    for(t_09 = 32'sd0; t_09 <= 32'sd7; t_09 = t_09 + 32'sd1) begin:create_mat_o_expanded_input9_gen
      assign create_mat_o_expanded_input9[t_09] = create_mat_o_expanded_input[9][t_09];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance10 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input9),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_9)  /* uint16 */
                                         );

  genvar t_010;
  generate
    for(t_010 = 32'sd0; t_010 <= 32'sd7; t_010 = t_010 + 32'sd1) begin:create_mat_o_expanded_input10_gen
      assign create_mat_o_expanded_input10[t_010] = create_mat_o_expanded_input[10][t_010];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance11 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input10),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_10)  /* uint16 */
                                         );

  genvar t_011;
  generate
    for(t_011 = 32'sd0; t_011 <= 32'sd7; t_011 = t_011 + 32'sd1) begin:create_mat_o_expanded_input11_gen
      assign create_mat_o_expanded_input11[t_011] = create_mat_o_expanded_input[11][t_011];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance12 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input11),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_11)  /* uint16 */
                                         );

  genvar t_012;
  generate
    for(t_012 = 32'sd0; t_012 <= 32'sd7; t_012 = t_012 + 32'sd1) begin:create_mat_o_expanded_input12_gen
      assign create_mat_o_expanded_input12[t_012] = create_mat_o_expanded_input[12][t_012];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance13 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input12),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_12)  /* uint16 */
                                         );

  genvar t_013;
  generate
    for(t_013 = 32'sd0; t_013 <= 32'sd7; t_013 = t_013 + 32'sd1) begin:create_mat_o_expanded_input13_gen
      assign create_mat_o_expanded_input13[t_013] = create_mat_o_expanded_input[13][t_013];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance14 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input13),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_13)  /* uint16 */
                                         );

  genvar t_014;
  generate
    for(t_014 = 32'sd0; t_014 <= 32'sd7; t_014 = t_014 + 32'sd1) begin:create_mat_o_expanded_input14_gen
      assign create_mat_o_expanded_input14[t_014] = create_mat_o_expanded_input[14][t_014];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance15 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input14),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_14)  /* uint16 */
                                         );

  genvar t_015;
  generate
    for(t_015 = 32'sd0; t_015 <= 32'sd7; t_015 = t_015 + 32'sd1) begin:create_mat_o_expanded_input15_gen
      assign create_mat_o_expanded_input15[t_015] = create_mat_o_expanded_input[15][t_015];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance16 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input15),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_15)  /* uint16 */
                                         );

  genvar t_016;
  generate
    for(t_016 = 32'sd0; t_016 <= 32'sd7; t_016 = t_016 + 32'sd1) begin:create_mat_o_expanded_input16_gen
      assign create_mat_o_expanded_input16[t_016] = create_mat_o_expanded_input[16][t_016];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance17 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input16),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_16)  /* uint16 */
                                         );

  genvar t_017;
  generate
    for(t_017 = 32'sd0; t_017 <= 32'sd7; t_017 = t_017 + 32'sd1) begin:create_mat_o_expanded_input17_gen
      assign create_mat_o_expanded_input17[t_017] = create_mat_o_expanded_input[17][t_017];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance18 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input17),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_17)  /* uint16 */
                                         );

  genvar t_018;
  generate
    for(t_018 = 32'sd0; t_018 <= 32'sd7; t_018 = t_018 + 32'sd1) begin:create_mat_o_expanded_input18_gen
      assign create_mat_o_expanded_input18[t_018] = create_mat_o_expanded_input[18][t_018];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance19 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input18),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_18)  /* uint16 */
                                         );

  genvar t_019;
  generate
    for(t_019 = 32'sd0; t_019 <= 32'sd7; t_019 = t_019 + 32'sd1) begin:create_mat_o_expanded_input19_gen
      assign create_mat_o_expanded_input19[t_019] = create_mat_o_expanded_input[19][t_019];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance20 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input19),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_19)  /* uint16 */
                                         );

  genvar t_020;
  generate
    for(t_020 = 32'sd0; t_020 <= 32'sd7; t_020 = t_020 + 32'sd1) begin:create_mat_o_expanded_input20_gen
      assign create_mat_o_expanded_input20[t_020] = create_mat_o_expanded_input[20][t_020];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance21 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input20),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_20)  /* uint16 */
                                         );

  genvar t_021;
  generate
    for(t_021 = 32'sd0; t_021 <= 32'sd7; t_021 = t_021 + 32'sd1) begin:create_mat_o_expanded_input21_gen
      assign create_mat_o_expanded_input21[t_021] = create_mat_o_expanded_input[21][t_021];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance22 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input21),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_21)  /* uint16 */
                                         );

  genvar t_022;
  generate
    for(t_022 = 32'sd0; t_022 <= 32'sd7; t_022 = t_022 + 32'sd1) begin:create_mat_o_expanded_input22_gen
      assign create_mat_o_expanded_input22[t_022] = create_mat_o_expanded_input[22][t_022];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance23 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input22),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_22)  /* uint16 */
                                         );

  genvar t_023;
  generate
    for(t_023 = 32'sd0; t_023 <= 32'sd7; t_023 = t_023 + 32'sd1) begin:create_mat_o_expanded_input23_gen
      assign create_mat_o_expanded_input23[t_023] = create_mat_o_expanded_input[23][t_023];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance24 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input23),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_23)  /* uint16 */
                                         );

  genvar t_024;
  generate
    for(t_024 = 32'sd0; t_024 <= 32'sd7; t_024 = t_024 + 32'sd1) begin:create_mat_o_expanded_input24_gen
      assign create_mat_o_expanded_input24[t_024] = create_mat_o_expanded_input[24][t_024];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance25 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input24),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_24)  /* uint16 */
                                         );

  genvar t_025;
  generate
    for(t_025 = 32'sd0; t_025 <= 32'sd7; t_025 = t_025 + 32'sd1) begin:create_mat_o_expanded_input25_gen
      assign create_mat_o_expanded_input25[t_025] = create_mat_o_expanded_input[25][t_025];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance26 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input25),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_25)  /* uint16 */
                                         );

  genvar t_026;
  generate
    for(t_026 = 32'sd0; t_026 <= 32'sd7; t_026 = t_026 + 32'sd1) begin:create_mat_o_expanded_input26_gen
      assign create_mat_o_expanded_input26[t_026] = create_mat_o_expanded_input[26][t_026];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance27 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input26),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_26)  /* uint16 */
                                         );

  genvar t_027;
  generate
    for(t_027 = 32'sd0; t_027 <= 32'sd7; t_027 = t_027 + 32'sd1) begin:create_mat_o_expanded_input27_gen
      assign create_mat_o_expanded_input27[t_027] = create_mat_o_expanded_input[27][t_027];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance28 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input27),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_27)  /* uint16 */
                                         );

  genvar t_028;
  generate
    for(t_028 = 32'sd0; t_028 <= 32'sd7; t_028 = t_028 + 32'sd1) begin:create_mat_o_expanded_input28_gen
      assign create_mat_o_expanded_input28[t_028] = create_mat_o_expanded_input[28][t_028];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance29 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input28),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_28)  /* uint16 */
                                         );

  genvar t_029;
  generate
    for(t_029 = 32'sd0; t_029 <= 32'sd7; t_029 = t_029 + 32'sd1) begin:create_mat_o_expanded_input29_gen
      assign create_mat_o_expanded_input29[t_029] = create_mat_o_expanded_input[29][t_029];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance30 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input29),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_29)  /* uint16 */
                                         );

  genvar t_030;
  generate
    for(t_030 = 32'sd0; t_030 <= 32'sd7; t_030 = t_030 + 32'sd1) begin:create_mat_o_expanded_input30_gen
      assign create_mat_o_expanded_input30[t_030] = create_mat_o_expanded_input[30][t_030];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance31 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input30),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_30)  /* uint16 */
                                         );

  genvar t_031;
  generate
    for(t_031 = 32'sd0; t_031 <= 32'sd7; t_031 = t_031 + 32'sd1) begin:create_mat_o_expanded_input31_gen
      assign create_mat_o_expanded_input31[t_031] = create_mat_o_expanded_input[31][t_031];
    end
  endgenerate

  mf_adder_tree u_adder_tree_instance32 (.i_clk(i_clk),
                                         .i_rstn(i_rstn),
                                         .i_mat_in(create_mat_o_expanded_input31),  /* ufix4 [8] */
                                         .i_valid(create_mat_valid_prop_out1),
                                         .o_value_out(adder_tree_dtc_out1_31)  /* uint16 */
                                         );
  assign adder_tree_o_value_out[0] = adder_tree_dtc_out1_0;
  assign adder_tree_o_value_out[1] = adder_tree_dtc_out1_1;
  assign adder_tree_o_value_out[2] = adder_tree_dtc_out1_2;
  assign adder_tree_o_value_out[3] = adder_tree_dtc_out1_3;
  assign adder_tree_o_value_out[4] = adder_tree_dtc_out1_4;
  assign adder_tree_o_value_out[5] = adder_tree_dtc_out1_5;
  assign adder_tree_o_value_out[6] = adder_tree_dtc_out1_6;
  assign adder_tree_o_value_out[7] = adder_tree_dtc_out1_7;
  assign adder_tree_o_value_out[8] = adder_tree_dtc_out1_8;
  assign adder_tree_o_value_out[9] = adder_tree_dtc_out1_9;
  assign adder_tree_o_value_out[10] = adder_tree_dtc_out1_10;
  assign adder_tree_o_value_out[11] = adder_tree_dtc_out1_11;
  assign adder_tree_o_value_out[12] = adder_tree_dtc_out1_12;
  assign adder_tree_o_value_out[13] = adder_tree_dtc_out1_13;
  assign adder_tree_o_value_out[14] = adder_tree_dtc_out1_14;
  assign adder_tree_o_value_out[15] = adder_tree_dtc_out1_15;
  assign adder_tree_o_value_out[16] = adder_tree_dtc_out1_16;
  assign adder_tree_o_value_out[17] = adder_tree_dtc_out1_17;
  assign adder_tree_o_value_out[18] = adder_tree_dtc_out1_18;
  assign adder_tree_o_value_out[19] = adder_tree_dtc_out1_19;
  assign adder_tree_o_value_out[20] = adder_tree_dtc_out1_20;
  assign adder_tree_o_value_out[21] = adder_tree_dtc_out1_21;
  assign adder_tree_o_value_out[22] = adder_tree_dtc_out1_22;
  assign adder_tree_o_value_out[23] = adder_tree_dtc_out1_23;
  assign adder_tree_o_value_out[24] = adder_tree_dtc_out1_24;
  assign adder_tree_o_value_out[25] = adder_tree_dtc_out1_25;
  assign adder_tree_o_value_out[26] = adder_tree_dtc_out1_26;
  assign adder_tree_o_value_out[27] = adder_tree_dtc_out1_27;
  assign adder_tree_o_value_out[28] = adder_tree_dtc_out1_28;
  assign adder_tree_o_value_out[29] = adder_tree_dtc_out1_29;
  assign adder_tree_o_value_out[30] = adder_tree_dtc_out1_30;
  assign adder_tree_o_value_out[31] = adder_tree_dtc_out1_31;
  assign o_data = adder_tree_o_value_out;

  always_ff @(posedge i_clk or negedge i_rstn)
    begin : adder_tree_valid_prop_process
      if (i_rstn == 1'b0) begin
        adder_tree_valid_prop_reg <= '{3{1'b0}};
      end
      else begin
        adder_tree_valid_prop_reg[0] <= create_mat_valid_prop_out1;
        adder_tree_valid_prop_reg[32'sd2:32'sd1] <= adder_tree_valid_prop_reg[32'sd1:32'sd0];
      end
    end

  assign adder_tree_valid_prop_out1 = adder_tree_valid_prop_reg[2];
  assign o_valid = adder_tree_valid_prop_out1;

endmodule  // mf_matrix_for_each_0

