// -------------------------------------------------------------
// 
// File Name: C:\Users\aherrman\source\repos\hdl-coder-examples\251028_144629_matrix_for_each_top\hdlsrc\matrix_for_each_wrapper\mf_matrix_for_each_top_pkg.sv
// Created: 2025-10-28 14:46:55
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// (c) Adam Herrmann
// 
// -------------------------------------------------------------



package mf_matrix_for_each_top_pkg;
  typedef  logic  [3:0] vec_unsigned_logic_4;

  typedef  logic  [31:0] vec_unsigned_logic_32;
  typedef  logic  [7:0] vec_unsigned_logic_8;

  typedef  logic  [15:0] vec_unsigned_logic_16;

endpackage: mf_matrix_for_each_top_pkg

